name: trendychef
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.2
  flutter_native_splash: ^2.4.7
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  meta: ^1.17.0
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  dio: ^5.9.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  http: ^1.6.0
  shared_preferences: ^2.5.3
  google_sign_in: ^7.2.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  video_player: ^2.10.1
  lottie: ^3.3.2
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.10
  webview_flutter_web: ^0.2.2+4
  go_router: ^17.0.0
  share_plus: ^12.0.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true

  web:
    generate: true
    image_path: assets/icons/app_icon.png
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/
  generate: true

  fonts:
    - family: inter
      fonts:
        - asset: assets\fonts\inter\Inter_28pt-Light.ttf
    - family: noto_sans
      fonts:
        - asset: assets\fonts\inter\NotoSansSyriac-Regular.ttf